version: '3'

services:
  postgresdb:
    image: postgres
    networks: 
      - orchestra
    environment: 
      POSTGRES_PASSWORD: docker
    ports: 
      - "5432:5432"
  networks:
    orchestra:
      external: true